### PR TITLE
feat: use Fauna Region Group endpoint

### PR DESCRIPTION
**Pull request by faunaee**
#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jensneuse** [comment]
Did you run make before running make test?

**Comment by faunaee** [comment]
@jensneuse I did not. I was taking the hint provided by the PR template to run `make test`. 

When I run `make` I see:

```
$ make
go install github.com/golang/protobuf/proto
go install github.com/golang/protobuf/protoc-gen-go
cd types && ./generate.sh
protoc-gen-go: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--go_out: protoc-gen-go: Plugin failed with status code 1.
make: *** [codegen] Error 1
```

I'm on:
* macOS Monterey 12.4
* go1.18.4 darwin/arm64

Apologies for operating as a naive user; I only wanted to add Region Group support for queries to Fauna's GraphQL API. Let me know if there is anything further I should be doing.

**Comment by jensneuse** [comment]
check this guide:
https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md

**Comment by faunaee** [comment]
I was missing the inclusion of `~/go/bin` in my PATH. The tests now complete successfully.

**Pull request merged**
